max_workers: 10
grpc_service_port: 50001
browser:
  headless: true
  verbose: false
crawler:
  cache_mode: "BYPASS"
  capture_mhtml: true
  screenshot: false
  pdf: false
  wait_for_images: true
  verbose: false
