# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: page_downloader.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'page_downloader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15page_downloader.proto\x12\x0epagedownloader\"\x1e\n\x0f\x44ownloadRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"=\n\x10\x44ownloadResponse\x12\x14\n\x0coriginal_url\x18\x01 \x01(\t\x12\x13\n\x0bzip_archive\x18\x02 \x01(\x0c\x32\x63\n\x0ePageDownloader\x12Q\n\x0c\x44ownloadPage\x12\x1f.pagedownloader.DownloadRequest\x1a .pagedownloader.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'page_downloader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOWNLOADREQUEST']._serialized_start=41
  _globals['_DOWNLOADREQUEST']._serialized_end=71
  _globals['_DOWNLOADRESPONSE']._serialized_start=73
  _globals['_DOWNLOADRESPONSE']._serialized_end=134
  _globals['_PAGEDOWNLOADER']._serialized_start=136
  _globals['_PAGEDOWNLOADER']._serialized_end=235
# @@protoc_insertion_point(module_scope)
